[default]
database_path = "db/user-db.db"
rocket_mountpoint = "/auth"
address = "0.0.0.0"
port = 8000
#workers = 8
max_blocking = 512
ident = "r_auth"
ip_header = "X-Real-IP"
keep_alive = 5
log_level = "normal"
cli_colors = true
secret_key = "F8oZ0rCDAAN/1THAUPHKnAprSOYfZrxi5Zj+ZEGqsqHtxHWn73z7Hi8oyAlinW/3qGHKwMypPFTmMRjHlQ2s2w==" #You want to change this. Generate a new one with: openssl rand -base64 64
tls = { certs = "tls/certs.pem", key = "tls/key.pem" } #openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -days 365
ctrlc = true
shutdown.grace = 2
shutdown.force = true
shutdown.timeout = 5

[debug]
address = "127.0.0.1"
log_level = "debug"

[release]
log_level = "critical"